Your email client doesn't support MIME-types inside of email messages. Please update your email client.

--mess_bound
Date: 2014-03-27 18:47
Content-type: multipart/alternative; boundary="alt_bound"

--alt_bound
Content-type: text/plain; charset="utf-8"

In this assignment you will develop a multi-threaded application that resolves domain names
to IP addresses, similar to the operation preformed each time you access a new website in your
web browser. The application is composed of two sub-systems, each with one thread pool:
requesters and resolvers. The sub-systems communicate with each other using a bounded
queue.  This type of system architecture is referred to as a Producer-Consumer architecture. It
is also used in search engine systems, like Google. In these systems, a set of crawler threads
place URLs onto a queue. This queue is then serviced by a set of indexer threads which
connect to the websites, parse the content, and then add an entry to a search index. Refer
to Figure 1 for a visual description.


NOTE: Please do not reply to this email, MailPri.me doesn't accept incoming messages.

Follow this link to unsubscribe: http://nomadmtb.com:8000/tracker/unsub/4cbe64f668283679ad505476c22bfb2d5eb7ee72

--alt_bound
Content-type: text/html; charset="utf-8"

<html style="font-family: Sans-Serif; width: 100%; background-color: #808080;">
<body style="margin: 0 auto; margin-top: 5px; padding: 0; width: 500px; font-size: 15px;">
<div style="background-color: #7CCBF2; padding: 5px;">

<IMG src="http://nomadmtb.com:8000/tracker/visit/4cbe64f668283679ad505476c22bfb2d5eb7ee72/087bc296295782997a6bae3c340225e90c2d6f5a.jpg" height="0px" width="0" />

<h1 style="margin: 0; padding: 0; text-align: center; color: #525453; margin-bottom: 15px;">Programming Assignment 4: DNS Name Resolution Engine</h1>
<div style="height: 1px; background-color: #525453; width: 100%"></div>
<h1 style="margin: 0; padding: 0; text-align: center; color: #525453; font-size: 20px; margin-top: 10px; margin-bottom: 10px;">CSCI 340: Operating Systems, Notifications</h1>

<div style="height: 1px; background-color: #525453; width: 100%"></div>

<table style="text-align: left; margin: 0 auto; margin-top: 10px; margin-bottom: 10px;">
<tr>
<td style="color: #525453;">To</td>
<td style="color: #FFFFFF; text-decoration: none;">nomadmtb@gmail.com</td>
<td style="color: #525453;">From</td>
<td style="color: #FFFFFF; text-decoration: none;">nomadmtb@gmail.com</td>
</tr>
</table>

</div>

<div style="padding: 5px; padding-top: 20px; padding-bottom: 20px; background-color: #ffffff; box-shadow: inset 0px 12px 5px -7px rgba(0,0,0,0.50);">
<p style="text-align: justify;">In this assignment you will develop a multi-threaded application that resolves domain names
to IP addresses, similar to the operation preformed each time you access a new website in your
web browser. The application is composed of two sub-systems, each with one thread pool:
requesters and resolvers. The sub-systems communicate with each other using a bounded
queue.  This type of system architecture is referred to as a Producer-Consumer architecture. It
is also used in search engine systems, like Google. In these systems, a set of crawler threads
place URLs onto a queue. This queue is then serviced by a set of indexer threads which
connect to the websites, parse the content, and then add an entry to a search index. Refer
to Figure 1 for a visual description.
</p>
<a href=http://www.bryancdixon.com/ target="_blank">http://www.bryancdixon.com/</a>
<p></p>
</div>

<div style="background-color: #7CCBF2; padding: 5px; font-size: 12px;">
<p>This messages has been sent using the mailing-campaign service MailPri.me.</p>
                        <p>You have been added to the mailing-list: CSCI 340: Operating Systems, Notifications by nomadmtb@gmail.com</p>
<p><b>NOTE:</b> Please do not reply to this email, MailPri.me <b>does not</b> accept incoming messages.</p>
<p></p>
<p>Follow this link to unsubscribe: <a style="text-decoration: none;" href="http://nomadmtb.com:8000/tracker/unsub/4cbe64f668283679ad505476c22bfb2d5eb7ee72">Unsubscribe</a></p>
<div style="height: 1px; background-color: #525453; width: 100%"></div>
<p style="text-align: center;"><a style="text-decoration: none;" href="http://www.mailpri.me">MailPrime</a></p>
</div>
</body>
</html>

--alt_bound--
--mess_bound--
